### ISSUE TITLE
Lipo: Update glyphs for 16F04, 16F10, 16F23 to look more like Lipo3

### ISSUE THREAD

**Issue by kienwt** [silnrsi/MiaoUnicode#7]
Unicode on top, Lipo3 on bottom

![16f04_16f10_16f23](https://cloud.githubusercontent.com/assets/18396131/14907422/4c29c5e2-0dfb-11e6-85d4-33c4127c53bb.JPG)

**Comment by jvgaultney** [comment]
That would be a major design change that would affect at least 28 glyphs, and would substantially change the overall style. Personally I don't think we can make such a major style change. If we really need a different style then we should strongly consider a separate, new design. Such would actually be a replacement for Shishan & Lipo3 rather than a variant of MiaoUnicode.

**Comment by jvgaultney** [comment]
Team agreed that it should be addressed through a different font project

**Comment by jvgaultney** [comment]
Team no longer agreed - reopening issue!

**Comment by jvgaultney** [comment]
First attempt at Lipo3-like versions. Glyphs names are miao_na.lpo, miao_ma.lpo, miao_nga.lpo. Before and after:
![image](https://cloud.githubusercontent.com/assets/4226750/19305836/b92126d0-906a-11e6-8cfc-73eda95ba328.png)

**Comment by kienwt** [comment]
The Lipo team likes it.
